### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by khiratsuka** [khiratsuka/Finger-Multi-EMG-Inference#2]
```
[train] 0epoch:  25%|██████████████████████████████████████▌                                                                                                                   | 1/4 [00:01<00:03,  1.03s/batch]
Traceback (most recent call last):
  File "EMGTrain.py", line 150, in <module>
    main()
  File "EMGTrain.py", line 94, in main
    train_loss, train_acc = training.train(net, Train_DataLoader, epoch, criterion, optimizer, device)
  File "/home/deeplearningbox/Documents/khiratsuka/2022/python/Finger-Multi-EMG-Inference/training.py", line 42, in train
    loss.backward()
  File "/home/deeplearningbox/.local/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/deeplearningbox/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 8.61 GiB (GPU 0; 23.70 GiB total capacity; 21.54 GiB already allocated; 878.06 MiB free; 21.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Comment by khiratsuka** [comment]
Linearを使うのではなくConv2DやLSTMを使ってモデルを作ってみる

**Comment by khiratsuka** [comment]
生波形データ長を8500→8500/4=2125へ
→センサは1kHz程度のサンプリング周波数でいいらしいので、平均とってデータ数減らしても十分そうだから

FFT後のデータ長を8500→8500/2=4250へ
→負の周波数分も含めて扱っていたが、正の部分のみ扱えば十分(サンプリング定理的にもOK)
